### ISSUE TITLE
Incorrectly including comparator in tests with SimpleQuantity?

### ISSUE THREAD

**Issue by pcosmog** [fhir-crucible/crucible#298]
The definition of the SimpleQuantity data type (http://hl7.org/fhir/datatypes.html#SimpleQuantity, http://hl7.org/fhir/simplequantity.profile.xml.html) says: "A fixed quantity (no comparator)"

In fact, this is the primary differentiator between between a SimpleQuantity and a Quantity; the SimpleQuantity does not allow a comparator.

However, a great number of the STU3 tests are passing a comparator inside a SimpleQuantity. For example, in the "Clinical Resources" test suite, the "Resource Test Allergy Intolerance" tests attempts to create an AllergyIntolerance record with a "range.low.comparator" element, as well as a range.high.comparator" element, and expects the create to succeed.

But in the definition of the Range element (http://hl7.org/fhir/datatypes.html#Range), both the low and high elements are of type "SimpleQuantity", and so the comparator element should not be allowed, and the create should fail?

This problem exists in 20+ tests, including:

X010 ActivityDefinition: Create New
X010 CapabilityStatement: Create New
X010 Claim: Create New
X010 FamilyMemberHistory: Create New

etc

**Comment by arscan** [comment]
You are correct.  One thing to note is that Crucible's resource generator doesn't do a great job of abiding to invariants, such as this one, as it is pretty difficult to generate data that works in a generic sense.  I put a fix in for this case, but I suspect there are other cases in the data that we generate unfortunately.

**Comment by arscan** [comment]
We deployed a fix, when you have a chance could you check it out and see if it looks good on your end?  Thanks!

**Comment by pcosmog** [comment]
I'm still seeing this issue in some places:

Test Suite: "Clinical Resources"
Test: "Resource Test Medication Request"
Step: "X010: MedicationRequest: Create New"
Error: "dosageInstruction[0].maxDosePerLifetime" is of type SimpleQuantity, but contains a comparator.

Test Suite: "Clinical Resources"
Test: "Resource Test Medication Statement"
Step: "X010: MedicationStatement: Create New"
Error: "dosage[0].maxDosePerAdministration" is of type SimpleQuantity, but contains a comparator.

Test Suite: "Clinical Resources"
Test: "Resource Test Observation"
Step: "X010: Observation: Create New"
Error: "component[0].referenceRange[0].low" is of type SimpleQuantity, but contains a comparator.

Test Suite: "Specialized Resources"
Test: "Resource Test Activity Definition"
Step: "X010: ActivityDefinition: Create New"
Error: "dosage[0].maxDosePerAdministration" is of type SimpleQuantity, but contains a comparator.

**Comment by arscan** [comment]
Updated again with these fixes, thanks for catching these for us.  Let me know if you see any more.

**Comment by pcosmog** [comment]
Still seeing this issue in:

Test Suite: "Clinical Resources"
Test: "Resource Test Observation"
Step: "X010: Observation: Create New"
Error: "component[0].referenceRange[0].low" is of type SimpleQuantity, but contains a comparator.

The other 3 are fixed.

**Comment by arscan** [comment]
Ah, sorry, missed that one.  Deployed a fix, please try again when you have a chance.

**Comment by pcosmog** [comment]
Confirmed fixed.
